services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "80:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=Swq8855830.

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Swq8855830.
      POSTGRES_DB: postgres
    ports:
      - "10086:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: